library customer_core;

export 'src/customer_app.dart';
export 'src/core/config/app_config.dart';
export 'src/core/config/ui_config.dart';
export 'src/core/config/key_config.dart';
export 'src/core/config/app_env.dart';
export 'src/core/constants/enums.dart';
export 'src/application/core/dependency_registrar.dart';
export 'src/core/routes/routes.dart';
export 'src/core/routes/routes.gr.dart';
export 'src/customer_initializer.dart';

// library customer_core;

// export 'src/application/auth/auth_provider.dart';
// export 'src/application/cart/cart_provider.dart';
// export 'src/application/core/api_response.dart';
// export 'src/application/core/base_controller.dart';
// export 'src/application/core/dependency_registrar.dart';
// export 'src/application/core/time_dropdown_provider.dart';
// export 'src/application/home/home_provider.dart';
// export 'src/application/notification/notification_provider.dart';
// export 'src/application/order/order_provider.dart';
// export 'src/application/payment/payment_provider.dart';
// export 'src/application/products/products_provider.dart';
// export 'src/application/promotion/promotions_provider.dart';
// export 'src/application/search/search_provider.dart';
// export 'src/application/shop/shop_provider.dart';
// export 'src/application/table/table_provider.dart';
// export 'src/application/theme/theme_provider.dart';
// export 'src/application/user/user_provider.dart';
// export 'src/core/config/app_config.dart';
// export 'src/core/config/app_env.dart';
// export 'src/core/constants/app_identifiers.dart';
// export 'src/core/global/global_variable.dart';
// export 'src/core/routes/routes.dart';
// export 'src/core/routes/routes.gr.dart';
// export 'src/core/theme/app_colors.dart';
// export 'src/core/theme/app_theme.dart';
// export 'src/core/theme/custom_text_styles.dart';
// export 'src/core/utils/alert_dialogs.dart';
// export 'src/core/utils/contact_utils.dart';
// export 'src/core/utils/date_utils.dart';
// export 'src/core/utils/material_color_generator.dart';
// export 'src/core/utils/ui_utils.dart';
// export 'src/core/utils/utils.dart';
// export 'src/customer_app.dart';
// export 'src/domain/cart/i_cart_repo.dart';
// export 'src/domain/cart/models/add_cart_products_details_model.dart';
// export 'src/domain/cart/models/add_product_cart_request_model.dart';
// export 'src/domain/cart/models/calculate_delivery_fee_data_model.dart';
// export 'src/domain/cart/models/cart_details_model.dart';
// export 'src/domain/checkout/i_checkout_repo.dart';
// export 'src/domain/checkout/models/calculate_take_away_details.dart';
// export 'src/domain/checkout/models/calculated_delivery_charge_details_model.dart';
// export 'src/domain/checkout/models/checkout_data_model.dart';
// export 'src/domain/checkout/models/payment_intent_details.dart';
// export 'src/domain/dependency_injection/injection_config.config.dart';
// export 'src/domain/dependency_injection/injection_config.dart';
// export 'src/domain/notification/i_notification_repo.dart';
// export 'src/domain/notification/models/notification_model.dart';
// export 'src/domain/offer/i_offer_repo.dart';
// export 'src/domain/offer/models/offer_details_model.dart';
// // export 'src/domain/offer/models/offer_details_model.freezed.dart';
// // export 'src/domain/offer/models/offer_details_model.g.dart';
// export 'src/domain/offer/models/validated_coupon_details.dart';
// // export 'src/domain/offer/models/validated_coupon_details.freezed.dart';
// // export 'src/domain/offer/models/validated_coupon_details.g.dart';
// export 'src/domain/promotion/i_promotion_repo.dart';
// export 'src/domain/promotion/models/promotions_model.dart';
// export 'src/domain/search/i_search_repo.dart';
// export 'src/domain/store/i_store_repo.dart';
// export 'src/domain/store/models/favourite_product_data_model.dart';
// export 'src/domain/store/models/featured_popular_products_data_model.dart';
// export 'src/domain/store/models/product_category_model.dart';
// export 'src/domain/store/models/product_details_model.dart';
// export 'src/domain/store/models/product_details_pagination.dart';
// export 'src/domain/store/models/store_delivery_slot_model.dart';
// export 'src/domain/store/models/store_settings_data_model.dart';
// export 'src/domain/store/models/store_timing_data_model.dart';
// export 'src/domain/table/i_table_repo.dart';
// export 'src/domain/table/models/reserve_dining_table.dart';
// export 'src/domain/table/models/table_reservation_details.dart';
// export 'src/domain/user/i_user_repo.dart';
// // export 'src/domain/user/i_user_shared_prefs.dart';
// export 'src/domain/user/models/add_new_adress_request_model.dart';
// export 'src/domain/user/models/order_history_raw_data_model.dart';
// export 'src/domain/user/models/user.dart';
// export 'src/domain/user/models/user_address_list_data_model.dart';
// export 'src/domain/user/models/user_consent_list_data_model.dart';
// export 'src/domain/user/models/user_login_request.dart';
// export 'src/domain/user/models/user_login_response.dart';
// export 'src/domain/user/models/user_register_request.dart';
// export 'src/domain/user/models/user_register_response.dart';
// export 'src/gen/assets.gen.dart';
// export 'src/infrastructure/cart/cart_repo.dart';
// export 'src/infrastructure/checkout/checkout_repo.dart';
// export 'src/infrastructure/core/api_manager/api_manager.dart';
// export 'src/infrastructure/core/end_points/end_points.dart';
// export 'src/infrastructure/core/failures/app_exceptions.dart';
// export 'src/infrastructure/notification/notification_shared_prefs_repo.dart';
// export 'src/infrastructure/offer/offer_repo.dart';
// export 'src/infrastructure/promotions/promotions_repo.dart';
// export 'src/infrastructure/search/search_repo.dart';
// export 'src/infrastructure/store/recent_search_product_prefs.dart';
// export 'src/infrastructure/store/store_repo.dart';
// export 'src/infrastructure/table/table_repo.dart';
// export 'src/infrastructure/theme/theme_shared_prefs_repo.dart';
// export 'src/infrastructure/user/user_repo.dart';
// export 'src/infrastructure/user/user_shared_prefs_repo.dart';
// export 'src/presentation/auth/forgot_otp.dart';
// export 'src/presentation/auth/forgot_screen.dart';
// export 'src/presentation/auth/login_screen.dart';
// export 'src/presentation/auth/otp_screen.dart';
// export 'src/presentation/auth/register_screen.dart';
// export 'src/presentation/home/home_screen.dart';
// export 'src/presentation/order_online/address/add_new_address_screen.dart';
// export 'src/presentation/order_online/address/user_address_screen.dart';
// export 'src/presentation/order_online/cart/cart_items_screen.dart';
// export 'src/presentation/order_online/cart/cart_screen.dart';
// export 'src/presentation/order_online/cart/checkout_details.dart';
// export 'src/presentation/order_online/cart/delivery_details_screen.dart';
// export 'src/presentation/order_online/cart/success_screen.dart';
// export 'src/presentation/order_online/categories/categories_screen.dart';
// export 'src/presentation/order_online/checkout/checkout_screen.dart';
// export 'src/presentation/order_online/coupen/coupen_screen.dart';
// export 'src/presentation/order_online/favourite/favourite_products_screen.dart';
// export 'src/presentation/order_online/home/order_online_home_screen.dart';
// export 'src/presentation/order_online/notification/notification_preference_screen.dart';
// export 'src/presentation/order_online/notification/notification_screen.dart';
// export 'src/presentation/order_online/order_online_screen.dart';
// export 'src/presentation/order_online/orders/order_history_screens.dart';
// export 'src/presentation/order_online/orders/view_order_screen.dart';
// export 'src/presentation/order_online/profile/delete_account_screen.dart';
// export 'src/presentation/order_online/profile/profile_screen.dart';
// export 'src/presentation/reservation/table_reservation_history.dart';
// export 'src/presentation/reservation/table_reservation_screen.dart';
// export 'src/presentation/splash/splash_screen.dart';
// export 'src/presentation/store/store_screen.dart';
// export 'src/presentation/welcome/welcome_screen.dart';
// export 'src/presentation/widgets/animated_search_bar.dart';
// export 'src/presentation/widgets/bottom_sheet_drag_handler.dart';
// export 'src/presentation/widgets/boucing_widget.dart';
// export 'src/presentation/widgets/button_progress.dart';
// export 'src/presentation/widgets/category_select_button.dart';
// export 'src/presentation/widgets/custom_back_button.dart';
// export 'src/presentation/widgets/custom_cart_increment_button.dart';
// export 'src/presentation/widgets/custom_close_icon.dart';
// export 'src/presentation/widgets/custom_nav_item.dart';
// export 'src/presentation/widgets/custom_painer_shape.dart';
// export 'src/presentation/widgets/custom_search_delegate.dart';
// export 'src/presentation/widgets/custom_swipe_button.dart';
// export 'src/presentation/widgets/custom_text_field.dart';
// export 'src/presentation/widgets/get_provider_view.dart';
// export 'src/presentation/widgets/manage_dish_sheets.dart';
// export 'src/presentation/widgets/product_details_tile.dart';
// export 'src/presentation/widgets/product_details_tile_search.dart';
// export 'src/presentation/widgets/qty_counter_button.dart';
// export 'src/presentation/widgets/search_bar_widget.dart';
// export 'src/presentation/widgets/shimmer_product_details_tile.dart';
// export 'src/presentation/widgets/time_dropdown.dart';
